### ISSUE TITLE
Version handling for APIs

### ISSUE THREAD

**Issue by Haydnspass** [ries-lab/DECODE_Cloud_WorkerAPI#6]
```yaml
api:
  versions:
    v0.10.0:
      image_url: https://hub.docker/decode/v0.10.0
      aws_batch:
        job_definition: decode-v0.10.0
        revision: 6
      entrypoints:
        train:
          config_path:
          data_path:
        fit:
          config_path:
          meta_path:
          data_path:
      hardware:
        gpu_mem: 10  # MB
    v0.11.0:
      entrypoints:
        train:
          config_path:
          data_path:
          data_2_path:
        fit:
          config_path:
          meta_path:
          data_path:
      hardware:
        gpu_mem: 10  # MB

    dev:

```

Worker facing API exemplary response;
```json

## WORKER FACING API
POST /JOB:
  version: v0.10.0
  body: {
    "entrypoint": "train",
    "config_path": "s3://bucket/config.yaml",
    "data_path": "s3://bucket/data.csv"
  }
  worker_filter: {
      "gpu_mem": "10GB",
      "gpu_model_name": "Tesla K80"
  }

GET /JOB:
  image_url: https://hub.docker/decode/v0.10.0
  body: {
    "entrypoint": "train",
    "entrypoint_args": {
      "config_path": "s3://bucket/config.yaml",
      "data_path": "s3://bucket/data.csv"
    }
  }
  hardware: {
    "gpu_mem": "10GB",
    "gpu_model_name": "Tesla K80"
  }
  meta: {
      "user_id": 1234,
  }
```
